runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

env_variables:
  GOOGLE_CLOUD_PROJECT: "bachecadellasicurezza"  # ID corretto del progetto

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
