services:
  - type: web
    name: webappbacheca
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: SPREADSHEET_ID
        sync: false
    healthCheckPath: /
    autoDeploy: true
    branch: master
